Repository scottcalebc/CS5523-final-project, pull requests merged in 2021-11, with the labels that each got.

#2 Feature test grpc
  .gitignore
  buildProto.sh
  interfaces/__init__.py
  interfaces/chatserver.proto
  interfaces/chatserver_pb2.py
  interfaces/chatserver_pb2_grpc.py
  requirements.txt
  src/__init__.py
  src/client.py
  src/server.py
Labels: enhancement

#10 Feature name service
  .gitattributes
  .gitignore
  buildProto.sh
  interfaces/__init__.py
  interfaces/chatserver.proto
  interfaces/chatserver_pb2.py
  interfaces/chatserver_pb2_grpc.py
  interfaces/globalmessage.proto
  interfaces/nameservice.proto
  requirements.txt
  src/client.py
  src/helper_funcs.py
  src/name_server.py
  src/server.py
Labels: enhancement

#13 Fix issue is possible networking hostname mismatch
  src/server.py
Labels: bug

#14 Update buildProto.sh
  buildProto.sh
Labels: bug, enhancement

#15 Feature chat server new interface
  interfaces/chatserver.proto
  interfaces/globalmessage.proto
  src/client.py
  src/server.py
Labels: enhancement

#16 Begin 0.1.0 release
  .gitattributes
  .gitignore
  buildProto.sh
  interfaces/chatserver.proto
  interfaces/globalmessage.proto
  interfaces/nameservice.proto
  requirements.txt
  src/client.py
  src/helper_funcs.py
  src/name_server.py
  src/server.py
Labels: documentation, enhancement

#18 Dev
  buildProto.sh
  src/client.py
  src/server.py
  test/test_client.py
  test/wordlist.txt
Labels: enhancement

#23 Feature database creation
  .DS_Store
  interfaces/databasefacade.proto
  serviceAccountKey.json
  src/database.py
Labels: enhancement

#22 Feature/client sync
  src/client.py
  src/name_server.py
  src/server.py
Labels: bug, enhancement
